source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HBCoreFramework_Example', :exclusive => true do
  pod 'HBCoreFramework', :path => '../'
end

target 'HBCoreFramework_Tests', :exclusive => true do
  pod 'HBCoreFramework', :path => '../'

  
end
